languageCode = "ru-ru"
defaultContentLanguage = "ru"
title = "Семинар «Группы Ли и теория инвариантов»"
baseURL = "http://halgebra.math.msu.su/"
    

[taxonomies]
	academic_year = "academic_year"

[blackfriday]
    fractions = false