backend:
  name: github
  repo: aperep/vinberg-algorithm
  branch: master

media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "2017-2018"
    label: "2017-2018"
    extension: "md"
    folder: "content/talk/2017-2018"
    create: true
    fields: # The fields each document in this collection have
      - {label: "Дата доклада", name: "display_date", widget: "date"}
      - {label: "Докладчик", name: "speaker", widget: "string"}
      - {label: "Название", name: "talk_title", widget: "string"}
      - {label: "Аннотация", name: "text", widget: "markdown"}
